services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=https://umattend-env-staging.vintasystem.com/api/v1
    container_name: umattend-client-staging
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://umattend-env-staging.vintasystem.com/api/v1
    networks:
      - umattend-network
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: umattend-server-staging
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    networks:
      - umattend-network
    volumes:
      - ./server/prisma:/app/prisma

  nginx:
    image: nginx:alpine
    container_name: umattend-nginx-staging
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - umattend-network
    depends_on:
      - client
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: umattend-certbot-staging
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  umattend-network:
    driver: bridge
