// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { deleteEventByEventId, getAuthLoginHistory, getUser, type Options, postAuthExchange, postAuthLogout, postAuthRefresh, postEvent, postEventAddOrganizerByEventId, postEventCheckInByEventIdByUserId, postEventCheckOutByEventIdByUserId, postUserOnboarding, putEventByEventId } from '../sdk.gen';
import type { DeleteEventByEventIdData, DeleteEventByEventIdError, DeleteEventByEventIdResponse, GetAuthLoginHistoryData, GetUserData, PostAuthExchangeData, PostAuthExchangeError, PostAuthExchangeResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthRefreshData, PostAuthRefreshError, PostAuthRefreshResponse, PostEventAddOrganizerByEventIdData, PostEventAddOrganizerByEventIdError, PostEventAddOrganizerByEventIdResponse, PostEventCheckInByEventIdByUserIdData, PostEventCheckInByEventIdByUserIdError, PostEventCheckInByEventIdByUserIdResponse, PostEventCheckOutByEventIdByUserIdData, PostEventCheckOutByEventIdByUserIdError, PostEventCheckOutByEventIdByUserIdResponse, PostEventData, PostEventError, PostEventResponse, PostUserOnboardingData, PostUserOnboardingError, PostUserOnboardingResponse, PutEventByEventIdData, PutEventByEventIdError, PutEventByEventIdResponse } from '../types.gen';

/**
 * Refresh access token
 *
 * Refresh the access token using a valid refresh token
 */
export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, AxiosError<PostAuthRefreshError>, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, AxiosError<PostAuthRefreshError>, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout user
 *
 * Logout the currently authenticated user
 */
export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<PostAuthLogoutResponse, AxiosError<PostAuthLogoutError>, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLogoutResponse, AxiosError<PostAuthLogoutError>, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Exchange authorization code
 *
 * Exchange authorization code for tokens
 */
export const postAuthExchangeMutation = (options?: Partial<Options<PostAuthExchangeData>>): UseMutationOptions<PostAuthExchangeResponse, AxiosError<PostAuthExchangeError>, Options<PostAuthExchangeData>> => {
    const mutationOptions: UseMutationOptions<PostAuthExchangeResponse, AxiosError<PostAuthExchangeError>, Options<PostAuthExchangeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthExchange({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getAuthLoginHistoryQueryKey = (options?: Options<GetAuthLoginHistoryData>) => createQueryKey('getAuthLoginHistory', options);

/**
 * Get login history
 *
 * Retrieve login history for the authenticated user
 */
export const getAuthLoginHistoryOptions = (options?: Options<GetAuthLoginHistoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuthLoginHistory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAuthLoginHistoryQueryKey(options)
    });
};

export const getUserQueryKey = (options?: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get user by ID
 *
 * Retrieve user information by user ID
 */
export const getUserOptions = (options?: Options<GetUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserQueryKey(options)
    });
};

/**
 * Onboard user
 *
 * Complete user onboarding process
 */
export const postUserOnboardingMutation = (options?: Partial<Options<PostUserOnboardingData>>): UseMutationOptions<PostUserOnboardingResponse, AxiosError<PostUserOnboardingError>, Options<PostUserOnboardingData>> => {
    const mutationOptions: UseMutationOptions<PostUserOnboardingResponse, AxiosError<PostUserOnboardingError>, Options<PostUserOnboardingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUserOnboarding({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create event
 *
 * Create a new event (Admin/CSG only)
 */
export const postEventMutation = (options?: Partial<Options<PostEventData>>): UseMutationOptions<PostEventResponse, AxiosError<PostEventError>, Options<PostEventData>> => {
    const mutationOptions: UseMutationOptions<PostEventResponse, AxiosError<PostEventError>, Options<PostEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete event
 *
 * Delete an existing event by ID (Admin/CSG only).
 */
export const deleteEventByEventIdMutation = (options?: Partial<Options<DeleteEventByEventIdData>>): UseMutationOptions<DeleteEventByEventIdResponse, AxiosError<DeleteEventByEventIdError>, Options<DeleteEventByEventIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteEventByEventIdResponse, AxiosError<DeleteEventByEventIdError>, Options<DeleteEventByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEventByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update event
 *
 * Update an existing event by ID (Admin/CSG only).
 */
export const putEventByEventIdMutation = (options?: Partial<Options<PutEventByEventIdData>>): UseMutationOptions<PutEventByEventIdResponse, AxiosError<PutEventByEventIdError>, Options<PutEventByEventIdData>> => {
    const mutationOptions: UseMutationOptions<PutEventByEventIdResponse, AxiosError<PutEventByEventIdError>, Options<PutEventByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putEventByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check in user
 *
 * Check in a user to an event (Admin/CSG/Organizer only)
 */
export const postEventCheckInByEventIdByUserIdMutation = (options?: Partial<Options<PostEventCheckInByEventIdByUserIdData>>): UseMutationOptions<PostEventCheckInByEventIdByUserIdResponse, AxiosError<PostEventCheckInByEventIdByUserIdError>, Options<PostEventCheckInByEventIdByUserIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventCheckInByEventIdByUserIdResponse, AxiosError<PostEventCheckInByEventIdByUserIdError>, Options<PostEventCheckInByEventIdByUserIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEventCheckInByEventIdByUserId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check out user
 *
 * Check out a user from an event (Admin/CSG/Organizer only)
 */
export const postEventCheckOutByEventIdByUserIdMutation = (options?: Partial<Options<PostEventCheckOutByEventIdByUserIdData>>): UseMutationOptions<PostEventCheckOutByEventIdByUserIdResponse, AxiosError<PostEventCheckOutByEventIdByUserIdError>, Options<PostEventCheckOutByEventIdByUserIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventCheckOutByEventIdByUserIdResponse, AxiosError<PostEventCheckOutByEventIdByUserIdError>, Options<PostEventCheckOutByEventIdByUserIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEventCheckOutByEventIdByUserId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add organizer
 *
 * Add an organizer to an event (Admin/CSG/Organizer only)
 */
export const postEventAddOrganizerByEventIdMutation = (options?: Partial<Options<PostEventAddOrganizerByEventIdData>>): UseMutationOptions<PostEventAddOrganizerByEventIdResponse, AxiosError<PostEventAddOrganizerByEventIdError>, Options<PostEventAddOrganizerByEventIdData>> => {
    const mutationOptions: UseMutationOptions<PostEventAddOrganizerByEventIdResponse, AxiosError<PostEventAddOrganizerByEventIdError>, Options<PostEventAddOrganizerByEventIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEventAddOrganizerByEventId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
