// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEventByEventIdData, DeleteEventByEventIdErrors, DeleteEventByEventIdResponses, DeleteEventRemoveOrganizerByEventIdData, DeleteEventRemoveOrganizerByEventIdErrors, DeleteEventRemoveOrganizerByEventIdResponses, GetAuthLoginHistoryData, GetAuthLoginHistoryErrors, GetAuthLoginHistoryResponses, GetEventByEventIdAttendeesData, GetEventByEventIdAttendeesErrors, GetEventByEventIdAttendeesResponses, GetEventByEventIdData, GetEventByEventIdErrors, GetEventByEventIdOrganizersData, GetEventByEventIdOrganizersErrors, GetEventByEventIdOrganizersResponses, GetEventByEventIdResponses, GetEventData, GetEventErrors, GetEventExportEventIdData, GetEventExportEventIdErrors, GetEventExportEventIdResponses, GetEventPastData, GetEventPastErrors, GetEventPastResponses, GetEventResponses, GetUserAttendedEventsData, GetUserAttendedEventsErrors, GetUserAttendedEventsResponses, GetUserData, GetUserErrors, GetUserEventsData, GetUserEventsErrors, GetUserEventsResponses, GetUserHostedEventsData, GetUserHostedEventsErrors, GetUserHostedEventsResponses, GetUserResponses, PostAuthExchangeData, PostAuthExchangeErrors, PostAuthExchangeResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostEventAddOrganizerByEventIdData, PostEventAddOrganizerByEventIdErrors, PostEventAddOrganizerByEventIdResponses, PostEventCheckInByEventIdByUserIdData, PostEventCheckInByEventIdByUserIdErrors, PostEventCheckInByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdData, PostEventCheckOutByEventIdByUserIdErrors, PostEventCheckOutByEventIdByUserIdResponses, PostEventData, PostEventErrors, PostEventResponses, PostUserOnboardingData, PostUserOnboardingErrors, PostUserOnboardingResponses, PutEventByEventIdData, PutEventByEventIdErrors, PutEventByEventIdResponses } from './types.gen';
import { zDeleteEventByEventIdData, zDeleteEventByEventIdResponse, zDeleteEventRemoveOrganizerByEventIdData, zDeleteEventRemoveOrganizerByEventIdResponse, zGetAuthLoginHistoryData, zGetAuthLoginHistoryResponse, zGetEventByEventIdAttendeesData, zGetEventByEventIdAttendeesResponse, zGetEventByEventIdData, zGetEventByEventIdOrganizersData, zGetEventByEventIdOrganizersResponse, zGetEventByEventIdResponse, zGetEventData, zGetEventExportEventIdData, zGetEventExportEventIdResponse, zGetEventPastData, zGetEventPastResponse, zGetEventResponse, zGetUserAttendedEventsData, zGetUserAttendedEventsResponse, zGetUserData, zGetUserEventsData, zGetUserEventsResponse, zGetUserHostedEventsData, zGetUserHostedEventsResponse, zGetUserResponse, zPostAuthExchangeData, zPostAuthExchangeResponse, zPostAuthLogoutData, zPostAuthLogoutResponse, zPostAuthRefreshData, zPostAuthRefreshResponse, zPostEventAddOrganizerByEventIdData, zPostEventAddOrganizerByEventIdResponse, zPostEventCheckInByEventIdByUserIdData, zPostEventCheckInByEventIdByUserIdResponse, zPostEventCheckOutByEventIdByUserIdData, zPostEventCheckOutByEventIdByUserIdResponse, zPostEventData, zPostEventResponse, zPostUserOnboardingData, zPostUserOnboardingResponse, zPutEventByEventIdData, zPutEventByEventIdResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Refresh access token
     *
     * Refresh the access token using a valid refresh token
     */
    public static postAuthRefresh<ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthRefreshData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthRefreshResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logout user
     *
     * Logout the currently authenticated user
     */
    public static postAuthLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthLogoutData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthLogoutResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/logout',
            ...options
        });
    }
    
    /**
     * Exchange authorization code
     *
     * Exchange authorization code for tokens
     */
    public static postAuthExchange<ThrowOnError extends boolean = false>(options: Options<PostAuthExchangeData, ThrowOnError>) {
        return (options.client ?? client).post<PostAuthExchangeResponses, PostAuthExchangeErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthExchangeData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthExchangeResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/exchange',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get login history
     *
     * Retrieve login history for the authenticated user
     */
    public static getAuthLoginHistory<ThrowOnError extends boolean = false>(options?: Options<GetAuthLoginHistoryData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAuthLoginHistoryResponses, GetAuthLoginHistoryErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetAuthLoginHistoryData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetAuthLoginHistoryResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/login-history',
            ...options
        });
    }
}

export class User {
    /**
     * Get user by ID
     *
     * Retrieve user information by user ID
     */
    public static getUser<ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user',
            ...options
        });
    }
    
    /**
     * Onboard user
     *
     * Complete user onboarding process
     */
    public static postUserOnboarding<ThrowOnError extends boolean = false>(options?: Options<PostUserOnboardingData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUserOnboardingResponses, PostUserOnboardingErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostUserOnboardingData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostUserOnboardingResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/onboarding',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Get user attended events
     *
     * Retrieve all events the user has attended (checked in and checked out)
     */
    public static getUserEvents<ThrowOnError extends boolean = false>(options?: Options<GetUserEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserEventsResponses, GetUserEventsErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserEventsData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserEventsResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/events',
            ...options
        });
    }
    
    /**
     * Get user attended events with details
     *
     * Retrieve all events the user has attended with event details including creator name and date/time
     */
    public static getUserAttendedEvents<ThrowOnError extends boolean = false>(options?: Options<GetUserAttendedEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserAttendedEventsResponses, GetUserAttendedEventsErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserAttendedEventsData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserAttendedEventsResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/attended-events',
            ...options
        });
    }
    
    /**
     * Get user hosted events
     *
     * Retrieve all events created/hosted by the user with attendee counts
     */
    public static getUserHostedEvents<ThrowOnError extends boolean = false>(options?: Options<GetUserHostedEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserHostedEventsResponses, GetUserHostedEventsErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserHostedEventsData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserHostedEventsResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/hosted-events',
            ...options
        });
    }
}

export class Event {
    /**
     * Get all events
     *
     * Retrieve all active (ongoing) events ordered by start time
     */
    public static getEvent<ThrowOnError extends boolean = false>(options?: Options<GetEventData, ThrowOnError>) {
        return (options?.client ?? client).get<GetEventResponses, GetEventErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetEventResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event',
            ...options
        });
    }
    
    /**
     * Create event
     *
     * Create a new event (Admin/CSG only)
     */
    public static postEvent<ThrowOnError extends boolean = false>(options: Options<PostEventData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventResponses, PostEventErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete event
     *
     * Delete an existing event by ID (Admin/CSG only).
     */
    public static deleteEventByEventId<ThrowOnError extends boolean = false>(options: Options<DeleteEventByEventIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteEventByEventIdResponses, DeleteEventByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zDeleteEventByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zDeleteEventByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}',
            ...options
        });
    }
    
    /**
     * Get event details by ID
     *
     * Retrieve detailed information about a specific event including check-in/check-out counts and edit permissions
     */
    public static getEventByEventId<ThrowOnError extends boolean = false>(options: Options<GetEventByEventIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetEventByEventIdResponses, GetEventByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetEventByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}',
            ...options
        });
    }
    
    /**
     * Update event
     *
     * Update an existing event by ID (Admin/CSG only).
     */
    public static putEventByEventId<ThrowOnError extends boolean = false>(options: Options<PutEventByEventIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutEventByEventIdResponses, PutEventByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPutEventByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPutEventByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Check in user
     *
     * Check in a user to an event (Admin/CSG/Organizer only)
     */
    public static postEventCheckInByEventIdByUserId<ThrowOnError extends boolean = false>(options: Options<PostEventCheckInByEventIdByUserIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventCheckInByEventIdByUserIdResponses, PostEventCheckInByEventIdByUserIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventCheckInByEventIdByUserIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventCheckInByEventIdByUserIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/check_in/{event_id}/{user_id}',
            ...options
        });
    }
    
    /**
     * Check out user
     *
     * Check out a user from an event (Admin/CSG/Organizer only)
     */
    public static postEventCheckOutByEventIdByUserId<ThrowOnError extends boolean = false>(options: Options<PostEventCheckOutByEventIdByUserIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventCheckOutByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventCheckOutByEventIdByUserIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventCheckOutByEventIdByUserIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/check_out/{event_id}/{user_id}',
            ...options
        });
    }
    
    /**
     * Add organizer
     *
     * Add an organizer to an event (Admin/CSG/Organizer only)
     */
    public static postEventAddOrganizerByEventId<ThrowOnError extends boolean = false>(options: Options<PostEventAddOrganizerByEventIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventAddOrganizerByEventIdResponses, PostEventAddOrganizerByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventAddOrganizerByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventAddOrganizerByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/add_organizer/{event_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Remove organizer
     *
     * Remove an organizer from an event (Admin/CSG/Organizer only). The event creator cannot be removed.
     */
    public static deleteEventRemoveOrganizerByEventId<ThrowOnError extends boolean = false>(options: Options<DeleteEventRemoveOrganizerByEventIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteEventRemoveOrganizerByEventIdResponses, DeleteEventRemoveOrganizerByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zDeleteEventRemoveOrganizerByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zDeleteEventRemoveOrganizerByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/remove_organizer/{event_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get all past events
     *
     * Retrieve all past (completed) events ordered by start time
     */
    public static getEventPast<ThrowOnError extends boolean = false>(options?: Options<GetEventPastData, ThrowOnError>) {
        return (options?.client ?? client).get<GetEventPastResponses, GetEventPastErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventPastData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetEventPastResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/past',
            ...options
        });
    }
    
    /**
     * Get paginated attendees by event ID
     *
     * Retrieve a paginated list of attendees for a specific event, including check-in/check-out details and pagination metadata. Supports search by name, student ID, or email.
     */
    public static getEventByEventIdAttendees<ThrowOnError extends boolean = false>(options: Options<GetEventByEventIdAttendeesData, ThrowOnError>) {
        return (options.client ?? client).get<GetEventByEventIdAttendeesResponses, GetEventByEventIdAttendeesErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventByEventIdAttendeesData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetEventByEventIdAttendeesResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}/attendees',
            ...options
        });
    }
    
    /**
     * Get event organizers
     *
     * Retrieve the list of organizers for a specific event (Admin/CSG/Organizer only).
     */
    public static getEventByEventIdOrganizers<ThrowOnError extends boolean = false>(options: Options<GetEventByEventIdOrganizersData, ThrowOnError>) {
        return (options.client ?? client).get<GetEventByEventIdOrganizersResponses, GetEventByEventIdOrganizersErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventByEventIdOrganizersData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetEventByEventIdOrganizersResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}/organizers',
            ...options
        });
    }
    
    /**
     * Export event attendees
     *
     * Export the list of attendees for a specific event to an Excel file `xlsx` (Admin/CSG/Organizer only).
     */
    public static getEventExportEventId<ThrowOnError extends boolean = false>(options: Options<GetEventExportEventIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetEventExportEventIdResponses, GetEventExportEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetEventExportEventIdData.parseAsync(data);
            },
            responseType: 'blob',
            responseValidator: async (data) => {
                return await zGetEventExportEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/export/:event_id',
            ...options
        });
    }
}
