// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEventByEventIdData, DeleteEventByEventIdErrors, DeleteEventByEventIdResponses, GetAuthLoginHistoryData, GetAuthLoginHistoryErrors, GetAuthLoginHistoryResponses, GetUserData, GetUserErrors, GetUserEventsData, GetUserEventsErrors, GetUserEventsResponses, GetUserResponses, PostAuthExchangeData, PostAuthExchangeErrors, PostAuthExchangeResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostEventAddOrganizerByEventIdData, PostEventAddOrganizerByEventIdErrors, PostEventAddOrganizerByEventIdResponses, PostEventCheckInByEventIdByUserIdData, PostEventCheckInByEventIdByUserIdErrors, PostEventCheckInByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdData, PostEventCheckOutByEventIdByUserIdErrors, PostEventCheckOutByEventIdByUserIdResponses, PostEventData, PostEventErrors, PostEventResponses, PostUserOnboardingData, PostUserOnboardingErrors, PostUserOnboardingResponses, PutEventByEventIdData, PutEventByEventIdErrors, PutEventByEventIdResponses } from './types.gen';
import { zDeleteEventByEventIdData, zDeleteEventByEventIdResponse, zGetAuthLoginHistoryData, zGetAuthLoginHistoryResponse, zGetUserData, zGetUserEventsData, zGetUserEventsResponse, zGetUserResponse, zPostAuthExchangeData, zPostAuthExchangeResponse, zPostAuthLogoutData, zPostAuthLogoutResponse, zPostAuthRefreshData, zPostAuthRefreshResponse, zPostEventAddOrganizerByEventIdData, zPostEventAddOrganizerByEventIdResponse, zPostEventCheckInByEventIdByUserIdData, zPostEventCheckInByEventIdByUserIdResponse, zPostEventCheckOutByEventIdByUserIdData, zPostEventCheckOutByEventIdByUserIdResponse, zPostEventData, zPostEventResponse, zPostUserOnboardingData, zPostUserOnboardingResponse, zPutEventByEventIdData, zPutEventByEventIdResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Authentication {
    /**
     * Refresh access token
     *
     * Refresh the access token using a valid refresh token
     */
    public static postAuthRefresh<ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthRefreshData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthRefreshResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logout user
     *
     * Logout the currently authenticated user
     */
    public static postAuthLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthLogoutData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthLogoutResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/logout',
            ...options
        });
    }
    
    /**
     * Exchange authorization code
     *
     * Exchange authorization code for tokens
     */
    public static postAuthExchange<ThrowOnError extends boolean = false>(options: Options<PostAuthExchangeData, ThrowOnError>) {
        return (options.client ?? client).post<PostAuthExchangeResponses, PostAuthExchangeErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostAuthExchangeData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostAuthExchangeResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/exchange',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get login history
     *
     * Retrieve login history for the authenticated user
     */
    public static getAuthLoginHistory<ThrowOnError extends boolean = false>(options?: Options<GetAuthLoginHistoryData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAuthLoginHistoryResponses, GetAuthLoginHistoryErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetAuthLoginHistoryData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetAuthLoginHistoryResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/auth/login-history',
            ...options
        });
    }
}

export class User {
    /**
     * Get user by ID
     *
     * Retrieve user information by user ID
     */
    public static getUser<ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user',
            ...options
        });
    }
    
    /**
     * Onboard user
     *
     * Complete user onboarding process
     */
    public static postUserOnboarding<ThrowOnError extends boolean = false>(options?: Options<PostUserOnboardingData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUserOnboardingResponses, PostUserOnboardingErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostUserOnboardingData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostUserOnboardingResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/onboarding',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Get user attended events
     *
     * Retrieve all events the user has attended (checked in and checked out)
     */
    public static getUserEvents<ThrowOnError extends boolean = false>(options?: Options<GetUserEventsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUserEventsResponses, GetUserEventsErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zGetUserEventsData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zGetUserEventsResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user/events',
            ...options
        });
    }
}

export class Event {
    /**
     * Create event
     *
     * Create a new event (Admin/CSG only)
     */
    public static postEvent<ThrowOnError extends boolean = false>(options: Options<PostEventData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventResponses, PostEventErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete event
     *
     * Delete an existing event by ID (Admin/CSG only).
     */
    public static deleteEventByEventId<ThrowOnError extends boolean = false>(options: Options<DeleteEventByEventIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteEventByEventIdResponses, DeleteEventByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zDeleteEventByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zDeleteEventByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}',
            ...options
        });
    }
    
    /**
     * Update event
     *
     * Update an existing event by ID (Admin/CSG only).
     */
    public static putEventByEventId<ThrowOnError extends boolean = false>(options: Options<PutEventByEventIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutEventByEventIdResponses, PutEventByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPutEventByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPutEventByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/{event_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Check in user
     *
     * Check in a user to an event (Admin/CSG/Organizer only)
     */
    public static postEventCheckInByEventIdByUserId<ThrowOnError extends boolean = false>(options: Options<PostEventCheckInByEventIdByUserIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventCheckInByEventIdByUserIdResponses, PostEventCheckInByEventIdByUserIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventCheckInByEventIdByUserIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventCheckInByEventIdByUserIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/check_in/{event_id}/{user_id}',
            ...options
        });
    }
    
    /**
     * Check out user
     *
     * Check out a user from an event (Admin/CSG/Organizer only)
     */
    public static postEventCheckOutByEventIdByUserId<ThrowOnError extends boolean = false>(options: Options<PostEventCheckOutByEventIdByUserIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventCheckOutByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventCheckOutByEventIdByUserIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventCheckOutByEventIdByUserIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/check_out/{event_id}/{user_id}',
            ...options
        });
    }
    
    /**
     * Add organizer
     *
     * Add an organizer to an event (Admin/CSG/Organizer only)
     */
    public static postEventAddOrganizerByEventId<ThrowOnError extends boolean = false>(options: Options<PostEventAddOrganizerByEventIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostEventAddOrganizerByEventIdResponses, PostEventAddOrganizerByEventIdErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zPostEventAddOrganizerByEventIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zPostEventAddOrganizerByEventIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/event/add_organizer/{event_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
