// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEventByEventIdData, DeleteEventByEventIdErrors, DeleteEventByEventIdResponses, GetAuthLoginHistoryData, GetAuthLoginHistoryErrors, GetAuthLoginHistoryResponses, GetUserData, GetUserErrors, GetUserResponses, PostAuthExchangeData, PostAuthExchangeErrors, PostAuthExchangeResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostEventAddOrganizerByEventIdData, PostEventAddOrganizerByEventIdErrors, PostEventAddOrganizerByEventIdResponses, PostEventCheckInByEventIdByUserIdData, PostEventCheckInByEventIdByUserIdErrors, PostEventCheckInByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdData, PostEventCheckOutByEventIdByUserIdErrors, PostEventCheckOutByEventIdByUserIdResponses, PostEventData, PostEventErrors, PostEventResponses, PostUserOnboardingData, PostUserOnboardingErrors, PostUserOnboardingResponses, PutEventByEventIdData, PutEventByEventIdErrors, PutEventByEventIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Refresh access token
 *
 * Refresh the access token using a valid refresh token
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Logout user
 *
 * Logout the currently authenticated user
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/logout',
        ...options
    });
};

/**
 * Exchange authorization code
 *
 * Exchange authorization code for tokens
 */
export const postAuthExchange = <ThrowOnError extends boolean = false>(options: Options<PostAuthExchangeData, ThrowOnError>) => {
    return (options.client ?? client).post<PostAuthExchangeResponses, PostAuthExchangeErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/exchange',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get login history
 *
 * Retrieve login history for the authenticated user
 */
export const getAuthLoginHistory = <ThrowOnError extends boolean = false>(options?: Options<GetAuthLoginHistoryData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAuthLoginHistoryResponses, GetAuthLoginHistoryErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/login-history',
        ...options
    });
};

/**
 * Get user by ID
 *
 * Retrieve user information by user ID
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user',
        ...options
    });
};

/**
 * Onboard user
 *
 * Complete user onboarding process
 */
export const postUserOnboarding = <ThrowOnError extends boolean = false>(options?: Options<PostUserOnboardingData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostUserOnboardingResponses, PostUserOnboardingErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/onboarding',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Create event
 *
 * Create a new event (Admin/CSG only)
 */
export const postEvent = <ThrowOnError extends boolean = false>(options: Options<PostEventData, ThrowOnError>) => {
    return (options.client ?? client).post<PostEventResponses, PostEventErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete event
 *
 * Delete an existing event by ID (Admin/CSG only).
 */
export const deleteEventByEventId = <ThrowOnError extends boolean = false>(options: Options<DeleteEventByEventIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteEventByEventIdResponses, DeleteEventByEventIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event/{event_id}',
        ...options
    });
};

/**
 * Update event
 *
 * Update an existing event by ID (Admin/CSG only).
 */
export const putEventByEventId = <ThrowOnError extends boolean = false>(options: Options<PutEventByEventIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutEventByEventIdResponses, PutEventByEventIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event/{event_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Check in user
 *
 * Check in a user to an event (Admin/CSG/Organizer only)
 */
export const postEventCheckInByEventIdByUserId = <ThrowOnError extends boolean = false>(options: Options<PostEventCheckInByEventIdByUserIdData, ThrowOnError>) => {
    return (options.client ?? client).post<PostEventCheckInByEventIdByUserIdResponses, PostEventCheckInByEventIdByUserIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event/check_in/{event_id}/{user_id}',
        ...options
    });
};

/**
 * Check out user
 *
 * Check out a user from an event (Admin/CSG/Organizer only)
 */
export const postEventCheckOutByEventIdByUserId = <ThrowOnError extends boolean = false>(options: Options<PostEventCheckOutByEventIdByUserIdData, ThrowOnError>) => {
    return (options.client ?? client).post<PostEventCheckOutByEventIdByUserIdResponses, PostEventCheckOutByEventIdByUserIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event/check_out/{event_id}/{user_id}',
        ...options
    });
};

/**
 * Add organizer
 *
 * Add an organizer to an event (Admin/CSG/Organizer only)
 */
export const postEventAddOrganizerByEventId = <ThrowOnError extends boolean = false>(options: Options<PostEventAddOrganizerByEventIdData, ThrowOnError>) => {
    return (options.client ?? client).post<PostEventAddOrganizerByEventIdResponses, PostEventAddOrganizerByEventIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/event/add_organizer/{event_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
