// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

export type PostAuthRefreshData = {
    body?: {
        /**
         * Refresh token (optional if provided in Authorization header)
         */
        refresh_token?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Bad request - Refresh token is required
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized - Token expired or invalid
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Not Found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            access_token?: string;
        };
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Bad request
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized - Token expired or authentication error
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Not Found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: {
        /**
         * Refresh token (optional if provided in Authorization header)
         */
        refresh_token?: string;
        success?: boolean;
        message?: string;
        data?: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthExchangeData = {
    /**
     * Error Response
     */
    body: {
        /**
         * Exchange Auth code
         */
        auth_code: string;
        /**
         * Exchange Error code
         */
        error_code: string;
    };
    path?: never;
    query?: never;
    url: '/auth/exchange';
};

export type PostAuthExchangeErrors = {
    /**
     * Bad request - Missing or invalid exchange code
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Not Found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostAuthExchangeError = PostAuthExchangeErrors[keyof PostAuthExchangeErrors];

export type PostAuthExchangeResponses = {
    /**
     * Code exchanged successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            access_token?: string;
            refresh_token?: string;
        };
    };
};

export type PostAuthExchangeResponse = PostAuthExchangeResponses[keyof PostAuthExchangeResponses];

export type GetAuthLoginHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login-history';
};

export type GetAuthLoginHistoryErrors = {
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type GetAuthLoginHistoryError = GetAuthLoginHistoryErrors[keyof GetAuthLoginHistoryErrors];

export type GetAuthLoginHistoryResponses = {
    /**
     * Login history retrieved successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            login_history?: Array<{
                id?: string;
                timestamp?: string;
                ipAddress?: string;
                userAgent?: string;
            }>;
        };
    };
};

export type GetAuthLoginHistoryResponse = GetAuthLoginHistoryResponses[keyof GetAuthLoginHistoryResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * User not found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            user?: {
                id?: string;
                email?: string;
                umindanao_email?: string;
                name?: string;
                role?: string;
                department?: string;
                program?: string;
                done_onboarding?: boolean;
            };
        };
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PostUserOnboardingData = {
    body?: {
        department: string;
        program: string;
    };
    path?: never;
    query?: never;
    url: '/user/onboarding';
};

export type PostUserOnboardingErrors = {
    /**
     * Bad request - Missing fields
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * User not found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostUserOnboardingError = PostUserOnboardingErrors[keyof PostUserOnboardingErrors];

export type PostUserOnboardingResponses = {
    /**
     * User onboarded successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            access_token?: string;
            user?: {
                id?: string;
                email?: string;
                name?: string;
                department?: string;
                program?: string;
                done_onboarding?: boolean;
            };
        };
    };
};

export type PostUserOnboardingResponse = PostUserOnboardingResponses[keyof PostUserOnboardingResponses];

export type PostEventData = {
    body: {
        /**
         * Event title
         */
        title: string;
        /**
         * Event description
         */
        description: string;
        /**
         * College/Department
         */
        department: string;
        /**
         * Event location
         */
        location: string;
        /**
         * Event capacity
         */
        capacity?: number;
        /**
         * All day event flag
         */
        all_day?: boolean;
        /**
         * Event start time (ISO 8601 format)
         */
        start_time: string;
        /**
         * Event end time (ISO 8601 format)
         */
        end_time: string;
        /**
         * Check out required flag
         */
        check_out_required?: boolean;
        /**
         * Event completion status
         */
        is_done?: boolean;
        /**
         * Custom form fields
         */
        form_fields?: Array<{
            /**
             * Form field name
             */
            field_name: string;
            /**
             * Form field type
             */
            fieldType: 'dropdown' | 'short_text' | 'long_text' | 'checkbox' | 'radio';
        }>;
    };
    path?: never;
    query?: never;
    url: '/event';
};

export type PostEventErrors = {
    /**
     * Bad request - Validation errors
     */
    400: {
        success?: boolean;
        message?: Array<{
            [key: string]: unknown;
        }>;
    };
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - Insufficient permissions
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostEventError = PostEventErrors[keyof PostEventErrors];

export type PostEventResponses = {
    /**
     * Event created successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            id?: string;
            title?: string;
            description?: string;
            department?: string;
            location?: string;
            capacity?: number;
            all_day?: boolean;
            start_time?: string;
            end_time?: string;
            check_out_required?: boolean;
            is_done?: boolean;
            created_by?: string;
        };
    };
};

export type PostEventResponse = PostEventResponses[keyof PostEventResponses];

export type DeleteEventByEventIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the event to delete.
         */
        event_id: string;
    };
    query?: never;
    url: '/event/{event_id}';
};

export type DeleteEventByEventIdErrors = {
    /**
     * Bad request - Event ID is required
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized - authentication required to delete an event
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - only Admin/CSG roles can delete events
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * Event not found - the specified event ID does not exist
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type DeleteEventByEventIdError = DeleteEventByEventIdErrors[keyof DeleteEventByEventIdErrors];

export type DeleteEventByEventIdResponses = {
    /**
     * Event deleted successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: null;
    };
};

export type DeleteEventByEventIdResponse = DeleteEventByEventIdResponses[keyof DeleteEventByEventIdResponses];

export type PutEventByEventIdData = {
    body: {
        /**
         * Event title
         */
        title: string;
        /**
         * Event description
         */
        description: string;
        /**
         * College/Department
         */
        department: string;
        /**
         * Event location
         */
        location: string;
        /**
         * Updated Event capacity
         */
        capacity?: number;
        /**
         * All day event flag
         */
        all_day?: boolean;
        /**
         * Event start time (ISO 8601 format)
         */
        start_time: string;
        /**
         * Event end time (ISO 8601 format)
         */
        end_time: string;
        /**
         * Check out required flag
         */
        check_out_required?: boolean;
        /**
         * Event completion status
         */
        is_done?: boolean;
        /**
         * Custom form fields
         */
        form_fields?: Array<{
            /**
             * Form field name
             */
            field_name: string;
            /**
             * Form field type
             */
            fieldType: 'dropdown' | 'short_text' | 'long_text' | 'checkbox' | 'radio';
        }>;
    };
    path: {
        /**
         * The unique ID of the event to update.
         */
        event_id: string;
    };
    query?: never;
    url: '/event/{event_id}';
};

export type PutEventByEventIdErrors = {
    /**
     * Bad request - invalid or missing update fields
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized - authentication required to update an event
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - only Admin/CSG roles can update events
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * Event not found - cannot update a non-existent event
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PutEventByEventIdError = PutEventByEventIdErrors[keyof PutEventByEventIdErrors];

export type PutEventByEventIdResponses = {
    /**
     * Event updated successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            id?: string;
            title?: string;
            description?: string;
            department?: string;
            location?: string;
            capacity?: number;
            all_day?: boolean;
            start_time?: string;
            end_time?: string;
            check_out_required?: boolean;
            is_done?: boolean;
        };
    };
};

export type PutEventByEventIdResponse = PutEventByEventIdResponses[keyof PutEventByEventIdResponses];

export type PostEventCheckInByEventIdByUserIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        user_id: string;
        /**
         * Event ID
         */
        event_id: string;
    };
    query?: never;
    url: '/event/check_in/{event_id}/{user_id}';
};

export type PostEventCheckInByEventIdByUserIdErrors = {
    /**
     * Bad request - Missing required fields
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - User has not completed onboarding
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * User or event not found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostEventCheckInByEventIdByUserIdError = PostEventCheckInByEventIdByUserIdErrors[keyof PostEventCheckInByEventIdByUserIdErrors];

export type PostEventCheckInByEventIdByUserIdResponses = {
    /**
     * User checked in successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            event_id?: string;
            event_name?: string;
            checked_in_at?: string;
            checked_in_by?: string;
        };
    };
};

export type PostEventCheckInByEventIdByUserIdResponse = PostEventCheckInByEventIdByUserIdResponses[keyof PostEventCheckInByEventIdByUserIdResponses];

export type PostEventCheckOutByEventIdByUserIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        user_id: string;
        /**
         * Event ID
         */
        event_id: string;
    };
    query?: never;
    url: '/event/check_out/{event_id}/{user_id}';
};

export type PostEventCheckOutByEventIdByUserIdErrors = {
    /**
     * Bad request - Missing required fields
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - User has not completed onboarding
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * User or event not found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostEventCheckOutByEventIdByUserIdError = PostEventCheckOutByEventIdByUserIdErrors[keyof PostEventCheckOutByEventIdByUserIdErrors];

export type PostEventCheckOutByEventIdByUserIdResponses = {
    /**
     * User checked out successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            event_id?: string;
            event_name?: string;
            checked_out_at?: string;
            checked_out_by?: string;
        };
    };
};

export type PostEventCheckOutByEventIdByUserIdResponse = PostEventCheckOutByEventIdByUserIdResponses[keyof PostEventCheckOutByEventIdByUserIdResponses];

export type PostEventAddOrganizerByEventIdData = {
    body: {
        /**
         * User ID of the organizer to add
         */
        userId: string;
    };
    path: {
        /**
         * Event ID
         */
        event_id: string;
    };
    query?: never;
    url: '/event/add_organizer/{event_id}';
};

export type PostEventAddOrganizerByEventIdErrors = {
    /**
     * Bad request - Missing required fields or validation errors
     */
    400: {
        success?: boolean;
        message?: string;
    };
    /**
     * Unauthorized
     */
    401: {
        success?: boolean;
        message?: string;
    };
    /**
     * Forbidden - Insufficient permissions
     */
    403: {
        success?: boolean;
        message?: string;
    };
    /**
     * Event or user not found
     */
    404: {
        success?: boolean;
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        success?: boolean;
        message?: string;
    };
};

export type PostEventAddOrganizerByEventIdError = PostEventAddOrganizerByEventIdErrors[keyof PostEventAddOrganizerByEventIdErrors];

export type PostEventAddOrganizerByEventIdResponses = {
    /**
     * Organizer added successfully
     */
    200: {
        success?: boolean;
        message?: string;
        data?: {
            id?: string;
            user_id?: string;
            event_id?: string;
            created_at?: string;
        };
    };
};

export type PostEventAddOrganizerByEventIdResponse = PostEventAddOrganizerByEventIdResponses[keyof PostEventAddOrganizerByEventIdResponses];
