// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPostAuthRefreshData = z.object({
    body: z.optional(z.object({
        refresh_token: z.optional(z.string())
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Token refreshed successfully
 */
export const zPostAuthRefreshResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        access_token: z.optional(z.string())
    }))
});

export const zPostAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Logged out successfully
 */
export const zPostAuthLogoutResponse = z.object({
    refresh_token: z.optional(z.string()),
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.null())
});

export const zPostAuthExchangeData = z.object({
    body: z.object({
        auth_code: z.string(),
        error_code: z.string()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Code exchanged successfully
 */
export const zPostAuthExchangeResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        access_token: z.optional(z.string()),
        refresh_token: z.optional(z.string())
    }))
});

export const zGetAuthLoginHistoryData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Login history retrieved successfully
 */
export const zGetAuthLoginHistoryResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        login_history: z.optional(z.array(z.object({
            id: z.optional(z.string()),
            timestamp: z.optional(z.iso.datetime()),
            ipAddress: z.optional(z.string()),
            userAgent: z.optional(z.string())
        })))
    }))
});

export const zGetUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * User retrieved successfully
 */
export const zGetUserResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        user: z.optional(z.object({
            id: z.optional(z.string()),
            email: z.optional(z.string()),
            umindanao_email: z.optional(z.string()),
            name: z.optional(z.string()),
            role: z.optional(z.string()),
            department: z.optional(z.string()),
            program: z.optional(z.string()),
            done_onboarding: z.optional(z.boolean())
        }))
    }))
});

export const zPostUserOnboardingData = z.object({
    body: z.optional(z.object({
        department: z.string(),
        program: z.string()
    })),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * User onboarded successfully
 */
export const zPostUserOnboardingResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        access_token: z.optional(z.string()),
        user: z.optional(z.object({
            id: z.optional(z.string()),
            email: z.optional(z.string()),
            name: z.optional(z.string()),
            department: z.optional(z.string()),
            program: z.optional(z.string()),
            done_onboarding: z.optional(z.boolean())
        }))
    }))
});

export const zGetUserEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * List of attended events retrieved successfully
 */
export const zGetUserEventsResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.array(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_in_at: z.optional(z.iso.datetime()),
        check_out_at: z.optional(z.iso.datetime())
    })))
});

export const zGetEventData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Events retrieved successfully
 */
export const zGetEventResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.array(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        department: z.optional(z.string()),
        location: z.optional(z.string()),
        capacity: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        all_day: z.optional(z.boolean()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_out_required: z.optional(z.boolean()),
        is_done: z.optional(z.boolean()),
        created_by: z.optional(z.string())
    })))
});

export const zPostEventData = z.object({
    body: z.object({
        title: z.string().min(1).max(140).default('Annual Tech Conference 2025'),
        description: z.string().min(20).max(500).default('Join us for an exciting day of technology talks, networking, and learning from industry experts.'),
        department: z.string().min(3).default('College of Computer Studies'),
        location: z.string().min(3).max(140).default('Main Auditorium, Building A'),
        capacity: z.optional(z.int()).default(100),
        all_day: z.optional(z.boolean()).default(false),
        start_time: z.iso.datetime().default('2025-10-15T09:00:00Z'),
        end_time: z.iso.datetime().default('2025-10-15T17:00:00Z'),
        check_out_required: z.optional(z.boolean()).default(false),
        is_done: z.optional(z.boolean()).default(false),
        form_fields: z.optional(z.array(z.object({
            field_name: z.string().min(1).max(140).default('Sample Field'),
            fieldType: z.enum([
                'dropdown',
                'short_text',
                'long_text',
                'checkbox',
                'radio'
            ])
        })).min(1)).default([
            {
                field_name: 'Dietary Restrictions',
                fieldType: 'short_text'
            },
            {
                field_name: 'T-Shirt Size',
                fieldType: 'dropdown'
            }
        ])
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Event created successfully
 */
export const zPostEventResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        department: z.optional(z.string()),
        location: z.optional(z.string()),
        capacity: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        all_day: z.optional(z.boolean()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_out_required: z.optional(z.boolean()),
        is_done: z.optional(z.boolean()),
        created_by: z.optional(z.string())
    }))
});

export const zDeleteEventByEventIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Event deleted successfully
 */
export const zDeleteEventByEventIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.null())
});

export const zGetEventByEventIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Event details retrieved successfully
 */
export const zGetEventByEventIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        department: z.optional(z.string()),
        location: z.optional(z.string()),
        capacity: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        all_day: z.optional(z.boolean()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_out_required: z.optional(z.boolean()),
        is_done: z.optional(z.boolean()),
        checkin_count: z.optional(z.number()),
        checkout_count: z.optional(z.number()),
        created_by: z.optional(z.string()),
        can_edit: z.optional(z.boolean()),
        user_attendance: z.optional(z.object({
            check_in_at: z.optional(z.union([
                z.iso.datetime(),
                z.null()
            ])),
            check_out_at: z.optional(z.union([
                z.iso.datetime(),
                z.null()
            ]))
        }))
    }))
});

export const zPutEventByEventIdData = z.object({
    body: z.object({
        title: z.string().min(1).max(140).default('Updated Annual Tech Conference 2025'),
        description: z.string().min(20).max(500).default('Updated Join us for an exciting day of technology talks, networking, and learning from industry experts.'),
        department: z.string().min(3).default('Updated College of Computer Studies'),
        location: z.string().min(3).max(140).default('Updated Main Auditorium, Building A'),
        capacity: z.optional(z.int()).default(100),
        all_day: z.optional(z.boolean()).default(false),
        start_time: z.iso.datetime().default('2025-10-15T09:00:00Z'),
        end_time: z.iso.datetime().default('2025-10-15T17:00:00Z'),
        check_out_required: z.optional(z.boolean()).default(false),
        is_done: z.optional(z.boolean()).default(false),
        form_fields: z.optional(z.array(z.object({
            field_name: z.string().min(1).max(140).default('Sample Field'),
            fieldType: z.enum([
                'dropdown',
                'short_text',
                'long_text',
                'checkbox',
                'radio'
            ])
        })).min(1)).default([
            {
                field_name: 'Dietary Restrictions',
                fieldType: 'short-text'
            },
            {
                field_name: 'T-Shirt Size',
                fieldType: 'dropdown'
            }
        ])
    }),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Event updated successfully
 */
export const zPutEventByEventIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        department: z.optional(z.string()),
        location: z.optional(z.string()),
        capacity: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        all_day: z.optional(z.boolean()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_out_required: z.optional(z.boolean()),
        is_done: z.optional(z.boolean())
    }))
});

export const zPostEventCheckInByEventIdByUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        student_id: z.string(),
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * User checked in successfully
 */
export const zPostEventCheckInByEventIdByUserIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        event_id: z.optional(z.string()),
        event_name: z.optional(z.string()),
        checked_in_at: z.optional(z.iso.datetime()),
        checked_in_by: z.optional(z.string())
    }))
});

export const zPostEventCheckOutByEventIdByUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        student_id: z.string(),
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * User checked out successfully
 */
export const zPostEventCheckOutByEventIdByUserIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        event_id: z.optional(z.string()),
        event_name: z.optional(z.string()),
        checked_out_at: z.optional(z.iso.datetime()),
        checked_out_by: z.optional(z.string())
    }))
});

export const zPostEventAddOrganizerByEventIdData = z.object({
    body: z.object({
        umindanao_email: z.string()
    }),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Organizer added successfully
 */
export const zPostEventAddOrganizerByEventIdResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        id: z.optional(z.string()),
        user_id: z.optional(z.string()),
        event_id: z.optional(z.string()),
        added_by: z.optional(z.string()),
        created_at: z.optional(z.iso.datetime())
    }))
});

export const zGetEventPastData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Events retrieved successfully
 */
export const zGetEventPastResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.array(z.object({
        id: z.optional(z.string()),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        department: z.optional(z.string()),
        location: z.optional(z.string()),
        capacity: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        all_day: z.optional(z.boolean()),
        start_time: z.optional(z.iso.datetime()),
        end_time: z.optional(z.iso.datetime()),
        check_out_required: z.optional(z.boolean()),
        is_done: z.optional(z.boolean()),
        created_by: z.optional(z.string())
    })))
});

export const zGetEventByEventIdAttendeesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)),
        limit: z.optional(z.int().gte(1))
    }))
});

/**
 * Attendees retrieved successfully
 */
export const zGetEventByEventIdAttendeesResponse = z.object({
    success: z.optional(z.boolean()),
    message: z.optional(z.string()),
    data: z.optional(z.object({
        data: z.optional(z.array(z.object({
            student: z.optional(z.object({
                id: z.optional(z.string()),
                user_id: z.optional(z.string()),
                student_id: z.optional(z.number()),
                name: z.optional(z.string()),
                umindanao_email: z.optional(z.string()),
                department: z.optional(z.string()),
                program: z.optional(z.string()),
                profile_picture: z.optional(z.string()),
                created_at: z.optional(z.iso.datetime()),
                updated_at: z.optional(z.iso.datetime()),
                check_in_at: z.optional(z.iso.datetime()),
                check_out_at: z.optional(z.iso.datetime()),
                check_in_by: z.optional(z.union([
                    z.string(),
                    z.null()
                ])),
                check_out_by: z.optional(z.union([
                    z.string(),
                    z.null()
                ]))
            }))
        }))),
        pagination: z.optional(z.object({
            page: z.optional(z.int()),
            limit: z.optional(z.int()),
            total: z.optional(z.int()),
            totalPages: z.optional(z.int())
        }))
    }))
});

export const zGetEventExportEventIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        event_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Binary Excel file content
 */
export const zGetEventExportEventIdResponse = z.string();
