'use client';

import { Globe, Monitor, MapPin, History } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { getAuthLoginHistoryOptions } from '@/api/client/@tanstack/react-query.gen';

const LoginHistorySkeleton = () => (
  <div className="space-y-3">
    {[...Array(5)].map((_, i) => (
      <div key={i} className="flex items-center gap-4 py-3">
        <Skeleton className="h-4 w-32" />
        <Skeleton className="h-4 w-24" />
        <Skeleton className="h-4 flex-1" />
      </div>
    ))}
  </div>
);

const formatLocation = (city?: string, region?: string, country?: string) => {
  const parts = [city, region, country].filter(Boolean);
  if (parts.length === 0) return 'Unknown Location';

  // If all are "Local", just show "Local Network"
  if (parts.every((part) => part === 'Local')) return 'Local Network';

  // Otherwise, show city and country (skip region to save space)
  if (city && country && city !== 'Local') {
    return `${city}, ${country}`;
  }

  return parts.join(', ');
};

// Temporary type until autogenerated types are updated
type LoginHistoryEntry = {
  id?: string;
  browser?: string;
  os?: string;
  city?: string;
  region?: string;
  country?: string;
};

export const LoginHistoryTable = () => {
  const { data, isLoading, isError } = useQuery({
    ...getAuthLoginHistoryOptions(),
    staleTime: 5 * 60 * 1000, // 5 minutes
    retry: 1
  });

  // Limit to 5 most recent entries
  const loginHistory = (data?.data?.login_history || []).slice(0, 5) as LoginHistoryEntry[];

  if (isError) {
    return (
      <Card className="border-border border shadow-sm">
        <CardHeader className="border-border border-b pb-4">
          <CardTitle className="text-foreground text-lg font-semibold">Login History</CardTitle>
          <CardDescription className="text-muted-foreground">View your recent login activity</CardDescription>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="text-muted-foreground flex flex-col items-center justify-center py-12 text-center">
            <Globe className="text-muted-foreground/50 mb-3 h-12 w-12" />
            <p className="text-sm">Failed to load login history</p>
            <p className="text-xs">Please try again later</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-border border shadow-sm">
      <CardHeader className="border-border border-b pb-4">
        <CardTitle className="text-foreground text-lg font-semibold">Login History</CardTitle>
        <CardDescription className="text-muted-foreground">View your 5 most recent login sessions</CardDescription>
      </CardHeader>
      <CardContent className="pt-6">
        {isLoading ? (
          <LoginHistorySkeleton />
        ) : loginHistory.length === 0 ? (
          <div className="text-muted-foreground flex flex-col items-center justify-center py-12 text-center">
            <History className="text-muted-foreground/50 mb-3 h-12 w-12" />
            <p className="text-sm font-medium">No login history found</p>
            <p className="text-xs">Your login activity will appear here</p>
          </div>
        ) : (
          <div className="border-border rounded-md border">
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead className="hidden md:table-cell">Location</TableHead>
                  <TableHead>Operating System</TableHead>
                  <TableHead>Browser</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loginHistory.map((entry) => {
                  const login = entry as LoginHistoryEntry;
                  const location = formatLocation(login.city, login.region, login.country);
                  const browser = login.browser || 'Unknown Browser';
                  const os = login.os || 'Unknown OS';

                  return (
                    <TableRow key={login.id} className="hover:bg-muted/50">
                      <TableCell className="hidden md:table-cell">
                        <div className="flex items-center gap-2">
                          <MapPin className="text-muted-foreground h-4 w-4 flex-shrink-0" />
                          <span className="text-muted-foreground text-sm">{location}</span>
                        </div>
                      </TableCell>
                      <TableCell className="font-medium">
                        <div className="flex items-center gap-2">
                          <Monitor className="text-muted-foreground h-4 w-4 flex-shrink-0" />
                          <span className="text-foreground text-sm">{os}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Globe className="text-muted-foreground h-4 w-4 flex-shrink-0" />
                          <span className="text-foreground text-sm">{browser}</span>
                        </div>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
